//! Light Token fundraiser: crowdfunding with rent-free vault.
//!
//! This test shows fundraiser patterns adapted for Light Token.
//!
//! 1. **Authority PDA owns the vault** — not the fundraiser account. This lets
//!    the authority sign vault withdrawals without needing account data
//!    (see `initialize.rs` `#[light_account(init, token::owner = authority)]`).
//!
//! 2. **Vault is rent-free** — it's a Light Token account sponsored by
//!    `RENT_SPONSOR`, eliminating the ~0.002 SOL rent per fundraiser.
//!
//! 3. **Validity proof for account creation** — `get_create_accounts_proof()`
//!    fetches a validity proof that the vault PDA's derived address does not
//!    yet exist in Light's address tree. Only needed in `initialize` (creating
//!    new state); `contribute`, `check_contributions`, and `refund` read
//!    existing accounts and need no proof.
//!
//! ## Token scenarios
//!
//! The vault is always a Light Token account. The contributor's account type
//! determines which CPI path `TransferInterfaceCpi` selects:
//!
//! | Test | Mint | Contributor accounts | Transfer path | Purpose |
//! |------|------|---------------------|---------------|---------|
//! | `test_fundraiser_spl` | SPL | SPL associated token accounts | `TransferInterfaceCpi` | SPL mints work with Light vault |
//! | `test_fundraiser_t22` | Token 2022 | Token 2022 associated token accounts | `TransferInterfaceCpi` | Token 2022 mints work with Light vault |
//! | `test_fundraiser_light` | Light | Associated Light Token accounts | `TransferCheckedCpi` | Rent-free path |
//! | `test_fundraiser_spl_light` | SPL | Associated Light Token accounts | `TransferCheckedCpi` | SPL mint, converted contributor accounts |
//! | `test_fundraiser_t22_light` | Token 2022 | Associated Light Token accounts | `TransferCheckedCpi` | Token 2022 mint, converted contributor accounts |
//!
//! For `Spl`/`Token2022`: contributor accounts are SPL/Token 2022, vault is Light →
//! `TransferInterfaceCpi` (with SPL interface PDA).
//!
//! For `Light`/`LightSpl`/`LightT22`: all accounts are Light Token →
//! `TransferCheckedCpi` (no interface PDA needed).
//!
//! `LightSpl`/`LightT22` convert tokens from SPL/Token 2022 associated token accounts
//! into associated Light Token accounts *before* the fundraiser starts (in `create_contributor`).
//! The fundraiser itself only sees Light Token accounts.
//!
//! ## Cold/hot lifecycle
//!
//! The vault is a PDA-owned Light Token account that turns cold when
//! sponsored rent expires. Loading a cold vault back to active requires
//! `VaultSeeds` / `LightAccountVariant::Vault` (generated by `#[light_program]`
//! when state derives `LightAccount`). Since `Fundraiser` uses standard
//! `#[account]`, these types aren't generated, so the test doesn't exercise
//! cold/hot lifecycle. See the escrow tests for full cold/hot coverage.

mod common;

use anchor_lang::{InstructionData, ToAccountMetas};
use common::{
    create_contributor, create_test_rpc, setup_fundraiser_test, FundraiserTestContext, TokenConfig,
};
use light_token::spl_interface::find_spl_interface_pda;
use light_client::interface::{get_create_accounts_proof, CreateAccountsProofInput};
use shared_test_utils::{
    helpers::verify_light_token_balance,
    light_tokens::create_light_ata,
    spl_tokens::create_spl_ata,
    t22_tokens::create_t22_ata,
    Indexer, LightProgramTest, Rpc, TestRpc, COMPRESSIBLE_CONFIG_V1, CPI_AUTHORITY_PDA,
    LIGHT_TOKEN_PROGRAM_ID, RENT_SPONSOR,
};
use solana_instruction::Instruction;
use solana_keypair::Keypair;
use solana_pubkey::Pubkey;
use solana_signer::Signer;

// ============================================================================
// Tests — one per token configuration: SPL, Token 2022, Light + 1 refund test.
// ============================================================================

/// SPL mint with SPL associated token accounts and Light Token vault.
///
/// All transfers use `TransferInterfaceCpi` (SPL ↔ Light Token vault)
/// with SPL interface PDAs. This is the baseline: same mint type as standard
/// SPL fundraiser, but the vault is a rent-free Light Token account.
#[tokio::test]
async fn test_fundraiser_spl() {
    let mut rpc = create_test_rpc().await;
    let ctx = setup_fundraiser_test(&mut rpc, TokenConfig::Spl, None).await;
    run_fundraiser_full_flow(&mut rpc, &ctx).await;
}

/// Token 2022 mint with Token 2022 associated token accounts and Light Token vault.
///
/// All transfers use `TransferInterfaceCpi` (Token 2022 ↔ Light Token vault)
/// with SPL interface PDAs.
#[tokio::test]
async fn test_fundraiser_t22() {
    let mut rpc = create_test_rpc().await;
    let ctx = setup_fundraiser_test(&mut rpc, TokenConfig::Token2022, None).await;
    run_fundraiser_full_flow(&mut rpc, &ctx).await;
}

/// Light Token mint + Light Token contributor accounts and Light Token vault.
///
/// All transfers use `TransferCheckedCpi`.
#[tokio::test]
async fn test_fundraiser_light() {
    let mut rpc = create_test_rpc().await;
    let ctx = setup_fundraiser_test(&mut rpc, TokenConfig::Light, None).await;
    run_fundraiser_full_flow(&mut rpc, &ctx).await;
}

/// SPL mint + Light Token contributor accounts. SPL tokens converted to associated
/// Light Token accounts in setup via `transfer_spl_to_light`.
///
/// All transfers use `TransferCheckedCpi`.
#[tokio::test]
async fn test_fundraiser_spl_light() {
    let mut rpc = create_test_rpc().await;
    let ctx = setup_fundraiser_test(&mut rpc, TokenConfig::LightSpl, None).await;
    run_fundraiser_full_flow(&mut rpc, &ctx).await;
}

/// Token 2022 mint + Light Token contributor accounts. Token 2022 tokens converted to
/// associated Light Token accounts in setup via `transfer_spl_to_light`.
///
/// All transfers use `TransferCheckedCpi`.
#[tokio::test]
async fn test_fundraiser_t22_light() {
    let mut rpc = create_test_rpc().await;
    let ctx = setup_fundraiser_test(&mut rpc, TokenConfig::LightT22, None).await;
    run_fundraiser_full_flow(&mut rpc, &ctx).await;
}

/// Light Token mint refund flow: deadline passes, target not met, contributors refund.
///
/// Uses `duration: 1` (1 day) to minimize warp time. Only 3 contributors
/// contribute (30% of target), so the target is not met. After advancing
/// past the deadline, each contributor calls `refund` to reclaim tokens.
#[tokio::test]
async fn test_fundraiser_refund() {
    let mut rpc = create_test_rpc().await;
    let ctx = setup_fundraiser_test(&mut rpc, TokenConfig::Light, Some(1)).await;
    run_fundraiser_refund_flow(&mut rpc, &ctx).await;
}

// ============================================================================
// Full Flow — Claim
// ============================================================================

/// Run the full fundraiser claim flow for any token configuration: SPL, Token 2022, Light.
///
/// 1. Initialize fundraiser: create vault, record terms
/// 2. Verify vault has 0 balance
/// 3. 10 contributors each contribute 10% of target
/// 4. Verify vault reached target
/// 5. Maker claims funds via check_contributions
/// 6. Verify final balances and account closure
async fn run_fundraiser_full_flow<R: Rpc + TestRpc + Indexer>(
    rpc: &mut R,
    ctx: &FundraiserTestContext,
) {
    initialize(rpc, ctx).await;

    verify_light_token_balance(rpc, ctx.vault_pda, 0, "vault (initial)").await;

    let contribution_amount = ctx.amount_to_raise * 10 / 100;
    let contributor_funding = contribution_amount * 2; // extra for fees

    for _i in 0..10 {
        let (contributor, contributor_ata) =
            create_contributor(rpc, ctx, contributor_funding).await;
        contribute(rpc, ctx, &contributor, contributor_ata, contribution_amount).await;
    }

    verify_light_token_balance(
        rpc,
        ctx.vault_pda,
        ctx.amount_to_raise,
        "vault (target reached)",
    )
    .await;

    let maker_ata = check_contributions(rpc, ctx).await;

    verify_light_token_balance(rpc, ctx.vault_pda, 0, "vault (after claim)").await;

    verify_light_token_balance(
        rpc,
        maker_ata,
        ctx.amount_to_raise,
        "maker_ata (after claim)",
    )
    .await;

    let fundraiser_account = rpc.get_account(ctx.fundraiser_pda).await.unwrap();
    assert!(
        fundraiser_account.is_none(),
        "Fundraiser account should be closed after check_contributions"
    );
}

// ============================================================================
// Refund Flow
// ============================================================================

/// Run the fundraiser refund flow: deadline passes, target not met, contributors reclaim.
///
/// 1. Initialize fundraiser with short duration (1 day)
/// 2. 3 contributors each contribute 10% (30% total — target not met)
/// 3. Advance clock past deadline (set unix_timestamp directly — no slot warp)
/// 4. Each contributor calls refund to reclaim tokens
/// 5. Verify vault empty, contributor balances restored, fundraiser still exists
async fn run_fundraiser_refund_flow(
    rpc: &mut LightProgramTest,
    ctx: &FundraiserTestContext,
) {
    initialize(rpc, ctx).await;

    verify_light_token_balance(rpc, ctx.vault_pda, 0, "vault (initial)").await;

    let contribution_amount = ctx.amount_to_raise * 10 / 100;
    let contributor_funding = contribution_amount * 2;
    let num_contributors = 3;

    let mut contributors: Vec<(Keypair, Pubkey)> = Vec::new();
    for _i in 0..num_contributors {
        let (contributor, contributor_ata) =
            create_contributor(rpc, ctx, contributor_funding).await;
        contribute(rpc, ctx, &contributor, contributor_ata, contribution_amount).await;
        contributors.push((contributor, contributor_ata));
    }

    let total_contributed = contribution_amount * num_contributors as u64;
    verify_light_token_balance(rpc, ctx.vault_pda, total_contributed, "vault (partial)").await;

    // Advance the Clock sysvar's unix_timestamp directly — `warp_epoch_forward`
    // only updates the slot, not unix_timestamp, in LiteSVM.
    //
    // We don't warp slots here because `warp_epoch_forward` turns all Light
    // accounts cold (vault, mints, contributor token accounts), and the fundraiser can't load
    // the vault from cold: `Fundraiser` doesn't derive `LightAccount`, so
    // `#[light_program]` doesn't generate `VaultSeeds` / `LightAccountVariant::Vault`
    // needed by `create_load_instructions`.
    //
    // Duration is 1 day. Refund requires `duration < elapsed_days`, so we need
    // the elapsed time to exceed 1 full day (86,400 seconds). Use 2 days.
    {
        use solana_sdk::clock::Clock;
        let mut clock = rpc.context.get_sysvar::<Clock>();
        clock.unix_timestamp += 2 * 86_400; // advance 2 days
        rpc.context.set_sysvar(&clock);
    }

    for (contributor, contributor_ata) in &contributors {
        refund(rpc, ctx, contributor, *contributor_ata).await;

        // Verify contributor received tokens back (started with contributor_funding,
        // contributed contribution_amount, got it back → net = contributor_funding)
        verify_light_token_balance(
            rpc,
            *contributor_ata,
            contributor_funding,
            "contributor_ata (after refund)",
        )
        .await;

        let (contributor_account_pda, _) = Pubkey::find_program_address(
            &[
                b"contributor",
                ctx.fundraiser_pda.as_ref(),
                contributor.pubkey().as_ref(),
            ],
            &ctx.program_id,
        );
        let contributor_acct = rpc.get_account(contributor_account_pda).await.unwrap();
        assert!(
            contributor_acct.is_none(),
            "Contributor account should be closed after refund"
        );
    }

    verify_light_token_balance(rpc, ctx.vault_pda, 0, "vault (after all refunds)").await;

    let fundraiser_account = rpc.get_account(ctx.fundraiser_pda).await.unwrap();
    assert!(
        fundraiser_account.is_some(),
        "Fundraiser account should still exist after refunds (only closed by check_contributions)"
    );
}

// ============================================================================
// Instruction Helpers
// ============================================================================

/// Fetch validity proof for vault creation, send `initialize` instruction.
async fn initialize<R: Rpc + TestRpc + Indexer>(
    rpc: &mut R,
    ctx: &FundraiserTestContext,
) {
    // Validity proof: verifies that the vault PDA's derived address does not
    // yet exist in Light's address tree.
    let proof_result = get_create_accounts_proof(
        rpc,
        &ctx.program_id,
        vec![CreateAccountsProofInput::pda(ctx.vault_pda)],
    )
    .await
    .unwrap();

    let accounts = fundraiser::accounts::Initialize {
        fee_payer: ctx.maker.pubkey(),
        authority: ctx.authority_pda,
        mint_to_raise: ctx.mint_pubkey,
        fundraiser: ctx.fundraiser_pda,
        vault: ctx.vault_pda,
        token_program: ctx.token_config.token_program_id(),
        system_program: solana_sdk::system_program::ID,
        light_token_program: Pubkey::new_from_array(LIGHT_TOKEN_PROGRAM_ID),
        light_token_config: COMPRESSIBLE_CONFIG_V1,
        light_token_rent_sponsor: RENT_SPONSOR,
        light_token_cpi_authority: CPI_AUTHORITY_PDA,
    };

    let data = fundraiser::instruction::Initialize {
        params: fundraiser::instructions::InitializeParams {
            create_accounts_proof: proof_result.create_accounts_proof,
            amount: ctx.amount_to_raise,
            duration: ctx.duration,
            vault_bump: ctx.vault_bump,
        },
    };

    // Remaining accounts: Light system accounts for proof verification
    // and address tree insertion (see `get_create_accounts_proof`).
    let ix = Instruction {
        program_id: ctx.program_id,
        accounts: [
            accounts.to_account_metas(None),
            proof_result.remaining_accounts,
        ]
        .concat(),
        data: data.data(),
    };

    rpc.create_and_send_transaction(
        &[ix],
        &ctx.payer.pubkey(),
        &[&ctx.payer, &ctx.maker],
    )
    .await
    .expect("initialize should succeed");
}

/// Send `contribute` instruction: contributor transfers tokens into the vault.
async fn contribute<R: Rpc + TestRpc + Indexer>(
    rpc: &mut R,
    ctx: &FundraiserTestContext,
    contributor: &Keypair,
    contributor_ata: Pubkey,
    amount: u64,
) {
    let (contributor_account_pda, _) = Pubkey::find_program_address(
        &[
            b"contributor",
            ctx.fundraiser_pda.as_ref(),
            contributor.pubkey().as_ref(),
        ],
        &ctx.program_id,
    );

    let accounts = fundraiser::accounts::Contribute {
        contributor: contributor.pubkey(),
        mint_to_raise: ctx.mint_pubkey,
        fundraiser: ctx.fundraiser_pda,
        contributor_account: contributor_account_pda,
        contributor_ata,
        vault: ctx.vault_pda,
        token_program: ctx.token_config.token_program_id(),
        system_program: solana_sdk::system_program::ID,
        light_token_program: Pubkey::new_from_array(LIGHT_TOKEN_PROGRAM_ID),
        light_token_rent_sponsor: RENT_SPONSOR,
        light_token_cpi_authority: CPI_AUTHORITY_PDA,
        spl_interface_pda: ctx
            .spl_interface
            .as_ref()
            .map(|i| i.pda)
            .unwrap_or_default(),
    };

    let (_, spl_interface_bump) = find_spl_interface_pda(&ctx.mint_pubkey, false);
    let data = fundraiser::instruction::Contribute { amount, spl_interface_bump };

    let ix = Instruction {
        program_id: ctx.program_id,
        accounts: accounts.to_account_metas(None),
        data: data.data(),
    };

    rpc.create_and_send_transaction(
        &[ix],
        &ctx.payer.pubkey(),
        &[&ctx.payer, contributor],
    )
    .await
    .expect("contribute should succeed");
}

/// Create maker's token account, send `check_contributions` instruction to claim funds.
///
/// Returns the maker's ATA pubkey.
async fn check_contributions<R: Rpc + TestRpc + Indexer>(
    rpc: &mut R,
    ctx: &FundraiserTestContext,
) -> Pubkey {
    let maker_ata = match ctx.token_config {
        TokenConfig::Spl | TokenConfig::LightSpl => {
            create_spl_ata(rpc, &ctx.payer, &ctx.mint_pubkey, &ctx.maker.pubkey()).await
        }
        TokenConfig::Token2022 | TokenConfig::LightT22 => {
            create_t22_ata(rpc, &ctx.payer, &ctx.mint_pubkey, &ctx.maker.pubkey()).await
        }
        TokenConfig::Light => {
            create_light_ata(rpc, &ctx.payer, &ctx.mint_pubkey, &ctx.maker.pubkey()).await
        }
    };

    let accounts = fundraiser::accounts::CheckContributions {
        fee_payer: ctx.maker.pubkey(),
        authority: ctx.authority_pda,
        mint_to_raise: ctx.mint_pubkey,
        fundraiser: ctx.fundraiser_pda,
        vault: ctx.vault_pda,
        maker_ata,
        token_program: ctx.token_config.token_program_id(),
        system_program: solana_sdk::system_program::ID,
        light_token_program: Pubkey::new_from_array(LIGHT_TOKEN_PROGRAM_ID),
        light_token_rent_sponsor: RENT_SPONSOR,
        light_token_cpi_authority: CPI_AUTHORITY_PDA,
        spl_interface_pda: ctx
            .spl_interface
            .as_ref()
            .map(|i| i.pda)
            .unwrap_or_default(),
    };

    let (_, spl_interface_bump) = find_spl_interface_pda(&ctx.mint_pubkey, false);
    let data = fundraiser::instruction::CheckContributions { spl_interface_bump };

    let ix = Instruction {
        program_id: ctx.program_id,
        accounts: accounts.to_account_metas(None),
        data: data.data(),
    };

    rpc.create_and_send_transaction(
        &[ix],
        &ctx.payer.pubkey(),
        &[&ctx.payer, &ctx.maker],
    )
    .await
    .expect("check_contributions should succeed");

    maker_ata
}

/// Send `refund` instruction: contributor reclaims tokens from vault after deadline.
async fn refund<R: Rpc + TestRpc + Indexer>(
    rpc: &mut R,
    ctx: &FundraiserTestContext,
    contributor: &Keypair,
    contributor_ata: Pubkey,
) {
    let (contributor_account_pda, _) = Pubkey::find_program_address(
        &[
            b"contributor",
            ctx.fundraiser_pda.as_ref(),
            contributor.pubkey().as_ref(),
        ],
        &ctx.program_id,
    );

    let accounts = fundraiser::accounts::Refund {
        contributor: contributor.pubkey(),
        maker: ctx.maker.pubkey(),
        authority: ctx.authority_pda,
        mint_to_raise: ctx.mint_pubkey,
        fundraiser: ctx.fundraiser_pda,
        contributor_account: contributor_account_pda,
        contributor_ata,
        vault: ctx.vault_pda,
        token_program: ctx.token_config.token_program_id(),
        system_program: solana_sdk::system_program::ID,
        light_token_program: Pubkey::new_from_array(LIGHT_TOKEN_PROGRAM_ID),
        light_token_rent_sponsor: RENT_SPONSOR,
        light_token_cpi_authority: CPI_AUTHORITY_PDA,
        spl_interface_pda: ctx
            .spl_interface
            .as_ref()
            .map(|i| i.pda)
            .unwrap_or_default(),
    };

    let (_, spl_interface_bump) = find_spl_interface_pda(&ctx.mint_pubkey, false);
    let data = fundraiser::instruction::Refund { spl_interface_bump };

    let ix = Instruction {
        program_id: ctx.program_id,
        accounts: accounts.to_account_metas(None),
        data: data.data(),
    };

    rpc.create_and_send_transaction(
        &[ix],
        &ctx.payer.pubkey(),
        &[&ctx.payer, contributor],
    )
    .await
    .expect("refund should succeed");
}
