[package]
name = "token-transfer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "token_transfer"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "light-sdk/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
light-sdk = { workspace = true }
light-sdk-types = { workspace = true }
light-sdk-macros = { workspace = true }
light-compressible = { workspace = true }
light-token = { workspace = true }
light-token-types = { workspace = true }
solana-pubkey = { workspace = true }
solana-msg = { workspace = true }
solana-program-error = { workspace = true }
solana-account-info = { workspace = true }

[dev-dependencies]
light-program-test = { workspace = true }
light-client = { workspace = true }
light-token-interface = { workspace = true }
tokio = { workspace = true }
solana-sdk = { workspace = true }
borsh = { workspace = true }
solana-instruction = { workspace = true }
solana-keypair = { workspace = true }
solana-signer = { workspace = true }

[lints.rust.unexpected_cfgs]
level = "allow"
check-cfg = ['cfg(target_os, values("solana"))']
